### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by FalxGod** [TotalWarArena-Modding/twa_unpack#1]
Dependencies are missing.
missing crate glob
Your library wont compile either

**Comment by Trolldemorted** [comment]
Cargo.toml lists the glob dependency properly:

```
[package]
name = "twa_unpack"
version = "0.1.0"
authors = ["Benedikt Constantin Radtke <benediktradtke@mailbox.tu-berlin.de>"]

[dependencies]
twa_pack_lib = { git = "https://github.com/TotalWarArena-Modding/twa_pack_lib" }
getopts = "0.2"
glob = "0.2"
```

Could you tell me more about the system you are trying to build twa_unpack on (operating system, rustup/rustc/cargo versions, target triple, and so on)?

**Comment by FalxGod** [comment]
Win10 Prof 64Bit
cloned repo.
Installed rust
rustc main.rs does not compile says it's missing the glob crate.
Am I derping?

**Comment by Trolldemorted** [comment]
If you use rustc I think you have to take care of dependency resolution yourself, `cargo build` should do the trick!

**Comment by FalxGod** [comment]
cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/TotalWarArena-Modding/twa_pack_lib`
 Downloading glob v0.2.11
 Downloading getopts v0.2.17
 Downloading byteorder v1.2.2
   Compiling byteorder v1.2.2
   Compiling getopts v0.2.17
   Compiling glob v0.2.11
   Compiling twa_pack_lib v0.1.0 (https://github.com/TotalWarArena-Modding/twa_pack_lib#acc2ea7d)
   Compiling twa_unpack v0.1.0 (file:///C:/Users/BaronNox/Documents/tools/twa_unpack-master/src)
error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> src\lib.rs:1:1
  |
1 | extern crate byteorder;
  | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> src\lib.rs:5:5
  |
5 | use byteorder::LittleEndian;
  |     ^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> src\lib.rs:6:5
  |
6 | use byteorder::ByteOrder;
  |     ^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
  --> src\lib.rs:75:9
   |
75 |         LittleEndian::read_u32(&self.raw_data[0x04..0x08])
   |         ^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
  --> src\lib.rs:79:9
   |
79 |         LittleEndian::read_u32(&self.raw_data[0x08..0x0C])
   |         ^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
  --> src\lib.rs:83:9
   |
83 |         LittleEndian::read_u32(&self.raw_data[0x0C..0x10])
   |         ^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
  --> src\lib.rs:87:9
   |
87 |         LittleEndian::read_u32(&self.raw_data[0x10..0x14])
   |         ^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
  --> src\lib.rs:91:9
   |
91 |         LittleEndian::read_u32(&self.raw_data[0x14..0x18])
   |         ^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
  --> src\lib.rs:95:9
   |
95 |         LittleEndian::read_u32(&self.raw_data[0x28..0x2C])
   |         ^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
   --> src\lib.rs:135:35
    |
135 |             let mut item_length = LittleEndian::read_u32(&self.raw_data[self.iterator_position..self.iterator_position + 4]);
    |                                   ^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
   --> src\lib.rs:145:25
    |
145 |                 let d = LittleEndian::read_u32(&self.raw_data[self.iterator_position..self.iterator_position + 4]);
    |                         ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 11 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `twa_unpack`.

To learn more, run the command again with --verbose.

**Comment by Trolldemorted** [comment]
That is odd, did you change anything in twa_unpack's files? Maybe there are some old files from your rustc executions hanging around, did you try `cargo clean` or re-cloning the repo?

Does `git diff` list any changes?

Which version of rustup, cargo and rustc are you using?

**Comment by Trolldemorted** [comment]
DId you solve this issue? I just cloned this repo on both a W10 and Ubuntu system, cd-ed into the directory, ran `cargo build` and it worked without issues.

**Comment by Trolldemorted** [comment]
If you or anyone has problems building twa_unpack please get in touch, but for now I'm gonna close this issue.
