### ISSUE TITLE
Arena PTS support

### ISSUE THREAD

**Issue by osaka04** [TotalWarArena-Modding/twa_unpack#2]
So today PTS for new patch launched and it seems unpacker (as well as RPFM) no longer works with it. I remember that with previous PTS versions it was working fine, so I guess CA changed something with files and possibly live version will have this problem in the future?

As for the problem itself, this is the error when trying to unpack data3.pack:

unpacking data3.pack: PackFile (encrypted index: true, encrypted content: false, padding: false, timestamped files: false)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 123, kind: Other, message: "The filename, directory name, or volume label syntax is incorrect." }', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

When trying to unpack wad.pack however, there is no error at all, but unpacker doesn't do anything either.

**Comment by Trolldemorted** [comment]
Could you upload one of the packs?

**Comment by osaka04** [comment]
[wad.zip](https://github.com/TotalWar-Modding/tw_unpack/files/2362081/wad.zip)

Can upload one of the bigger packs too, but it would take some time with my slow internet.

**Comment by Trolldemorted** [comment]
Seems like they changed (at least) the index encryption -.-

**Comment by osaka04** [comment]
Since latest patch, unpacker doesn't work with pack files from regular TWA client as well

**Comment by Trolldemorted** [comment]
Sorry for the long delay, but now its here: [tw_unpack 0.1.11](https://github.com/TotalWar-Modding/tw_unpack/releases/tag/0.1.11) supports unpacking TWA packs again! 🎉
